=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/xsd/AgathionData.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="agathion" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:int" name="id" use="optional"/>
								<xs:attribute type="xs:byte" name="enchant" use="optional"/>
								<xs:attribute type="xs:string" name="mainSkill" use="optional"/>
								<xs:attribute type="xs:string" name="subSkill" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/AgathionData.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/AgathionData.xsd">
	<!-- Agathion Aries - 60 days -->
	<agathion id="90894" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" />
	<!-- Agathion Aries -->
	<agathion id="90895" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" />
	<!-- Agathion Joy -->
	<agathion id="90896" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1;51034,1" />
	<!-- Agathion Joy - 7 days -->
	<agathion id="90897" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1;51034,1" />
	<!-- Agathion Pisces - 15 days -->
	<agathion id="90902" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" />
	<!-- Agathion Cancer - 15 days -->
	<agathion id="90903" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" />
	<!-- Agathion Pisces - 30 days -->
	<agathion id="91111" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" subSkill="51100,1" />
	<!-- Agathion Cancer - 30 days -->
	<agathion id="91112" enchant="0" mainSkill="51030,1;51031,1;51032,1;51033,1" subSkill="51100,1" />
	<!-- Agathion Rudolph - 2 hours -->
	<agathion id="90909" enchant="0" mainSkill="51035,1;51037,1" subSkill="51036,1" />
	<!-- Penitent Agathion -->
	<agathion id="91004" enchant="0" mainSkill="51068,1" />
	<!-- Agathion Ignis -->
	<agathion id="91129" enchant="0" mainSkill="51089,1" subSkill="51093,1" />
	<!-- Agathion Nebula -->
	<agathion id="91130" enchant="0" mainSkill="51090,1" subSkill="51094,1" />
	<!-- Agathion Procella -->
	<agathion id="91131" enchant="0" mainSkill="51091,1" subSkill="51095,1" />
	<!-- Agathion Petram -->
	<agathion id="91132" enchant="0" mainSkill="51092,1" subSkill="51096,1" />
	<!-- Agathion Virgo -->
	<agathion id="48048" enchant="0" subSkill="54004,1" />
	<agathion id="48048" enchant="1" subSkill="54004,2" />
	<agathion id="48048" enchant="2" subSkill="54004,3" />
	<agathion id="48048" enchant="3" subSkill="54004,4" />
	<agathion id="48048" enchant="4" subSkill="54004,5" />
	<agathion id="48048" enchant="5" subSkill="54004,6" />
	<agathion id="48048" enchant="6" subSkill="54004,7" />
	<agathion id="48048" enchant="7" subSkill="54004,8" />
	<agathion id="48048" enchant="8" subSkill="54004,9" />
	<agathion id="48048" enchant="9" subSkill="54004,10" />
	<agathion id="48048" enchant="10" subSkill="54004,11" />
	<!-- Agathion Capricorn -->
	<agathion id="48049" enchant="0" subSkill="54006,1" />
	<agathion id="48049" enchant="1" subSkill="54006,2" />
	<agathion id="48049" enchant="2" subSkill="54006,3" />
	<agathion id="48049" enchant="3" subSkill="54006,4" />
	<agathion id="48049" enchant="4" subSkill="54006,5" />
	<agathion id="48049" enchant="5" subSkill="54006,6" />
	<agathion id="48049" enchant="6" subSkill="54006,7" />
	<agathion id="48049" enchant="7" subSkill="54006,8" />
	<agathion id="48049" enchant="8" subSkill="54006,9" />
	<agathion id="48049" enchant="9" subSkill="54006,10" />
	<agathion id="48049" enchant="10" subSkill="54006,11" />
	<!-- Agathion Libra -->
	<agathion id="48050" enchant="0" subSkill="54007,1" />
	<agathion id="48050" enchant="1" subSkill="54007,2" />
	<agathion id="48050" enchant="2" subSkill="54007,3" />
	<agathion id="48050" enchant="3" subSkill="54007,4" />
	<agathion id="48050" enchant="4" subSkill="54007,5" />
	<agathion id="48050" enchant="5" subSkill="54007,6" />
	<agathion id="48050" enchant="6" subSkill="54007,7" />
	<agathion id="48050" enchant="7" subSkill="54007,8" />
	<agathion id="48050" enchant="8" subSkill="54007,9" />
	<agathion id="48050" enchant="9" subSkill="54007,10" />
	<agathion id="48050" enchant="10" subSkill="54007,11" />
	<!-- Agathion Taurus -->
	<agathion id="48052" enchant="0" subSkill="54000,1" />
	<agathion id="48052" enchant="1" subSkill="54000,2" />
	<agathion id="48052" enchant="2" subSkill="54000,3" />
	<agathion id="48052" enchant="3" subSkill="54000,4" />
	<agathion id="48052" enchant="4" subSkill="54000,5" />
	<agathion id="48052" enchant="5" subSkill="54000,6" />
	<agathion id="48052" enchant="6" subSkill="54000,7" />
	<agathion id="48052" enchant="7" subSkill="54000,8" />
	<agathion id="48052" enchant="8" subSkill="54000,9" />
	<agathion id="48052" enchant="9" subSkill="54000,10" />
	<agathion id="48052" enchant="10" subSkill="54000,11" />
	<!-- Agathion Leo -->
	<agathion id="48053" enchant="0" subSkill="54001,1" />
	<agathion id="48053" enchant="1" subSkill="54001,2" />
	<agathion id="48053" enchant="2" subSkill="54001,3" />
	<agathion id="48053" enchant="3" subSkill="54001,4" />
	<agathion id="48053" enchant="4" subSkill="54001,5" />
	<agathion id="48053" enchant="5" subSkill="54001,6" />
	<agathion id="48053" enchant="6" subSkill="54001,7" />
	<agathion id="48053" enchant="7" subSkill="54001,8" />
	<agathion id="48053" enchant="8" subSkill="54001,9" />
	<agathion id="48053" enchant="9" subSkill="54001,10" />
	<agathion id="48053" enchant="10" subSkill="54001,11" />
	<!-- Agathion Gemini -->
	<agathion id="48054" enchant="0" subSkill="54008,1" />
	<agathion id="48054" enchant="1" subSkill="54008,2" />
	<agathion id="48054" enchant="2" subSkill="54008,3" />
	<agathion id="48054" enchant="3" subSkill="54008,4" />
	<agathion id="48054" enchant="4" subSkill="54008,5" />
	<agathion id="48054" enchant="5" subSkill="54008,6" />
	<agathion id="48054" enchant="6" subSkill="54008,7" />
	<agathion id="48054" enchant="7" subSkill="54008,8" />
	<agathion id="48054" enchant="8" subSkill="54008,9" />
	<agathion id="48054" enchant="9" subSkill="54008,10" />
	<agathion id="48054" enchant="10" subSkill="54008,11" />
	<!-- Agathion Scorpio -->
	<agathion id="48055" enchant="0" subSkill="54002,1" />
	<agathion id="48055" enchant="1" subSkill="54002,2" />
	<agathion id="48055" enchant="2" subSkill="54002,3" />
	<agathion id="48055" enchant="3" subSkill="54002,4" />
	<agathion id="48055" enchant="4" subSkill="54002,5" />
	<agathion id="48055" enchant="5" subSkill="54002,6" />
	<agathion id="48055" enchant="6" subSkill="54002,7" />
	<agathion id="48055" enchant="7" subSkill="54002,8" />
	<agathion id="48055" enchant="8" subSkill="54002,9" />
	<agathion id="48055" enchant="9" subSkill="54002,10" />
	<agathion id="48055" enchant="10" subSkill="54002,11" />
	<!-- Agathion Aquarius -->
	<agathion id="48056" enchant="0" subSkill="54005,1" />
	<agathion id="48056" enchant="1" subSkill="54005,2" />
	<agathion id="48056" enchant="2" subSkill="54005,3" />
	<agathion id="48056" enchant="3" subSkill="54005,4" />
	<agathion id="48056" enchant="4" subSkill="54005,5" />
	<agathion id="48056" enchant="5" subSkill="54005,6" />
	<agathion id="48056" enchant="6" subSkill="54005,7" />
	<agathion id="48056" enchant="7" subSkill="54005,8" />
	<agathion id="48056" enchant="8" subSkill="54005,9" />
	<agathion id="48056" enchant="9" subSkill="54005,10" />
	<agathion id="48056" enchant="10" subSkill="54005,11" />
	<!-- Agathion Sagittarius -->
	<agathion id="48058" enchant="0" subSkill="54003,1" />
	<agathion id="48058" enchant="1" subSkill="54003,2" />
	<agathion id="48058" enchant="2" subSkill="54003,3" />
	<agathion id="48058" enchant="3" subSkill="54003,4" />
	<agathion id="48058" enchant="4" subSkill="54003,5" />
	<agathion id="48058" enchant="5" subSkill="54003,6" />
	<agathion id="48058" enchant="6" subSkill="54003,7" />
	<agathion id="48058" enchant="7" subSkill="54003,8" />
	<agathion id="48058" enchant="8" subSkill="54003,9" />
	<agathion id="48058" enchant="9" subSkill="54003,10" />
	<agathion id="48058" enchant="10" subSkill="54003,11" />
	<!-- High Quality Agathion Virgo - Fire Dragon -->
	<agathion id="91606" enchant="0" subSkill="54004,12" />
	<agathion id="91606" enchant="1" subSkill="54004,13" />
	<agathion id="91606" enchant="2" subSkill="54004,14" />
	<agathion id="91606" enchant="3" subSkill="54004,15" />
	<agathion id="91606" enchant="4" subSkill="54004,16" />
	<agathion id="91606" enchant="5" subSkill="54004,17" />
	<agathion id="91606" enchant="6" subSkill="54004,18;51346,1" />
	<agathion id="91606" enchant="7" subSkill="54004,19;51346,2" />
	<agathion id="91606" enchant="8" subSkill="54004,20;51346,3" />
	<agathion id="91606" enchant="9" subSkill="54004,21;51346,4" />
	<agathion id="91606" enchant="10" subSkill="54004,22;51346,5" />
	<!-- High Quality Agathion Capricorn - Fire Dragon -->
	<agathion id="91607" enchant="0" subSkill="54006,12" />
	<agathion id="91607" enchant="1" subSkill="54006,13" />
	<agathion id="91607" enchant="2" subSkill="54006,14" />
	<agathion id="91607" enchant="3" subSkill="54006,15" />
	<agathion id="91607" enchant="4" subSkill="54006,16" />
	<agathion id="91607" enchant="5" subSkill="54006,17" />
	<agathion id="91607" enchant="6" subSkill="54006,18;51347,1" />
	<agathion id="91607" enchant="7" subSkill="54006,19;51347,2" />
	<agathion id="91607" enchant="8" subSkill="54006,20;51347,3" />
	<agathion id="91607" enchant="9" subSkill="54006,21;51347,4" />
	<agathion id="91607" enchant="10" subSkill="54006,22;51347,5" />
	<!-- High Quality Agathion Libra - Fire Dragon -->
	<agathion id="91608" enchant="0" subSkill="54007,12" />
	<agathion id="91608" enchant="1" subSkill="54007,13" />
	<agathion id="91608" enchant="2" subSkill="54007,14" />
	<agathion id="91608" enchant="3" subSkill="54007,15" />
	<agathion id="91608" enchant="4" subSkill="54007,16" />
	<agathion id="91608" enchant="5" subSkill="54007,17" />
	<agathion id="91608" enchant="6" subSkill="54007,18;51348,1" />
	<agathion id="91608" enchant="7" subSkill="54007,19;51348,2" />
	<agathion id="91608" enchant="8" subSkill="54007,20;51348,3" />
	<agathion id="91608" enchant="9" subSkill="54007,21;51348,4" />
	<agathion id="91608" enchant="10" subSkill="54007,22;51348,5" />
	<!-- High Quality Agathion Taurus - Fire Dragon -->
	<agathion id="91609" enchant="0" subSkill="54000,12" />
	<agathion id="91609" enchant="1" subSkill="54000,13" />
	<agathion id="91609" enchant="2" subSkill="54000,14" />
	<agathion id="91609" enchant="3" subSkill="54000,15" />
