=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/xsd/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element maxOccurs="unbounded" name="item">
					<xs:complexType>
						<xs:sequence>
							<xs:choice maxOccurs="unbounded">
								<xs:element maxOccurs="unbounded" name="set">
									<xs:complexType>
										<xs:attribute name="name" type="xs:string" use="required" />
										<xs:attribute name="val" type="xs:string" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="skills">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="skill">
												<xs:complexType>
													<xs:attribute name="id" type="xs:int" use="required" />
													<xs:attribute name="level" type="xs:unsignedByte" use="required" />
													<xs:attribute name="type" type="xs:string" use="optional" />
													<xs:attribute name="type_value" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="type_chance" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="stats">
									<xs:complexType>
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="stat">
												<xs:complexType>
													<xs:simpleContent>
														<xs:extension base="xs:decimal">
															<xs:attribute name="type" type="xs:string" use="required" />
														</xs:extension>
													</xs:simpleContent>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="cond">
									<xs:complexType>
										<xs:sequence>
											<xs:element minOccurs="0" name="target">
												<xs:complexType>
													<xs:attribute name="levelRange" type="xs:string" use="required" />
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="and">
												<xs:complexType>
													<xs:sequence>
														<xs:element maxOccurs="unbounded" name="player">
															<xs:complexType>
																<xs:attribute name="castle" type="xs:byte" use="optional" />
																<xs:attribute name="pledgeClass" type="xs:byte" use="optional" />
																<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
																<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
											<xs:element minOccurs="0" name="player">
												<xs:complexType>
													<xs:attribute name="flyMounted" type="xs:boolean" use="optional" />
													<xs:attribute name="isHero" type="xs:boolean" use="optional" />
													<xs:attribute name="sex" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="level" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="chaotic" type="xs:boolean" use="optional" />
													<xs:attribute name="levelRange" type="xs:string" use="optional" />
													<xs:attribute name="insideZoneId" type="xs:string" use="optional" />
													<xs:attribute name="class_id_restriction" type="xs:string" use="optional" />
													<xs:attribute name="categoryType" type="xs:string" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="addName" type="xs:unsignedByte" use="optional" />
										<xs:attribute name="msgId" type="xs:unsignedShort" use="required" />
									</xs:complexType>
								</xs:element>
								<xs:element name="capsuled_items">
									<xs:complexType mixed="true">
										<xs:sequence>
											<xs:element maxOccurs="unbounded" name="item">
												<xs:complexType>
													<xs:attribute name="id" type="xs:integer" use="required" />
													<xs:attribute name="min" type="xs:unsignedLong" use="required" />
													<xs:attribute name="max" type="xs:unsignedLong" use="required" />
													<xs:attribute name="chance" type="xs:decimal" use="required" />
													<xs:attribute name="minEnchant" type="xs:unsignedByte" use="optional" />
													<xs:attribute name="maxEnchant" type="xs:unsignedByte" use="optional" />
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="id" type="xs:unsignedInt" use="required" />
						<xs:attribute name="name" type="xs:string" use="required" />
						<xs:attribute name="type" type="xs:string" use="required" />
						<xs:attribute name="additionalName" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/47900-47999.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="47927" name="Magic Fan - Blue" additionalName="Sealed" type="Weapon">
		<!-- A magic fan that can be used for making fire and cooling in hot weather. A beautiful accessory for every costume. <font color=ff6666><Unavailable to Sylphs/ Vanguard Riders/ Assassins.></font> -->
		<set name="icon" val="icon.ev_kr_13th_present_blue" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="BLUNT" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_magic_weapon" val="true" />
		<set name="is_freightable" val="true" />
		<set name="weight" val="150" />
		<stats>
			<stat type="pAtk">1</stat>
			<stat type="mAtk">1</stat>
			<stat type="rCrit">6</stat>
			<stat type="accCombat">8</stat>
			<stat type="pAtkSpd">379</stat>
			<stat type="randomDamage">1</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
	<item id="47928" name="Magic Woodpile" type="EtcItem">
		<!-- Double-click to use a magic woodpile for one player. If you have the Magic Fan equipped, you can use the skills Breeze and Gust to set fire to the woodpile. -->
		<set name="icon" val="icon.ev_firewood_seed_solo" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="is_stackable" val="true" />
		<set name="material" val="WOOD" />
	</item>
	<item id="47929" name="Large Magic Woodpile" type="EtcItem">
		<!-- Double-click to use a magic woodpile for party use. If you have the Magic Fan equipped, you can use the skills Breeze and Gust to set fire to the woodpile. -->
		<set name="icon" val="icon.ev_firewood_seed_party" />
		<set name="default_action" val="SKILL_REDUCE" />
		<set name="is_stackable" val="true" />
		<set name="material" val="WOOD" />
	</item>
	<item id="47945" name="Magic Fan - Yellow" additionalName="Sealed" type="Weapon">
		<!-- A magic fan that can be used for making fire and cooling in hot weather. A beautiful accessory for every costume. <font color=ff6666><Unavailable to Sylphs/ Vanguard Riders/ Assassins.></font> -->
		<set name="icon" val="icon.ev_kr_13th_present_yellow" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="BLUNT" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_magic_weapon" val="true" />
		<set name="is_freightable" val="true" />
		<set name="weight" val="150" />
		<stats>
			<stat type="pAtk">1</stat>
			<stat type="mAtk">1</stat>
			<stat type="rCrit">6</stat>
			<stat type="accCombat">8</stat>
			<stat type="pAtkSpd">379</stat>
			<stat type="randomDamage">1</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/39700-39799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="39719" name="Monster Only: Kruk's Staff" additionalName="Sealed" type="Weapon">
		<!-- Monster weapon. -->
		<set name="icon" val="icon.wp_fishing4" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="POLE" />
		<set name="bodypart" val="lrhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="D" />
		<set name="material" val="STEEL" />
		<set name="weight" val="205" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_destroyable" val="false" />
		<set name="is_depositable" val="false" />
		<set name="is_sellable" val="false" />
		<stats>
			<stat type="pAtk">92</stat>
			<stat type="mAtk">54</stat>
			<stat type="rCrit">8</stat>
			<stat type="accCombat">-3.75</stat>
			<stat type="pAtkSpd">325</stat>
			<stat type="randomDamage">10</stat>
			<stat type="pAtkRange">80</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/99300-99399.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="99357" name="Emerald Weapon: Rapier" type="Weapon">
		<set name="icon" val="BranchSys3.Icon.g_beam_sword" />
		<set name="default_action" val="EQUIP" />
		<set name="weapon_type" val="RAPIER" />
		<set name="bodypart" val="rhand" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="B" />
		<set name="material" val="STEEL" />
		<set name="weight" val="144" />
		<set name="soulshots" val="1" />
		<set name="spiritshots" val="1" />
		<set name="is_sellable" val="false" />
		<set name="is_freightable" val="true" />
		<stats>
			<stat type="randomDamage">10</stat>
			<stat type="pAtkRange">40</stat>
		</stats>
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/33700-33799.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="33778" name="A-grade Soulshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Soulshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SOULSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="33785" name="A-grade Spiritshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Spiritshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SPIRITSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
	<item id="33792" name="Blessed A-grade Spiritshot" additionalName="Not Available" type="EtcItem">
		<!-- The item is not available. Take it to the Game Assistant to exchange for a new Spiritshot. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="SPIRITSHOT" />
		<set name="immediate_effect" val="true" />
		<set name="crystal_type" val="A" />
		<set name="material" val="PAPER" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_stackable" val="true" />
	</item>
</list>

=== ax-grymyr/l2dn-server/L2Dn/L2Dn.GameServer/DataPack/stats/items/20600-20699.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/items.xsd">
	<item id="20662" name="Agathion Uthanka" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A bracelet for summoning Uthanka. -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="lbracelet" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="SILVER" />
		<set name="weight" val="150" />
		<set name="is_tradable" val="false" />
		<set name="is_dropable" val="false" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="is_freightable" val="true" />
		<skills>
			<skill id="21109" level="1" type="ON_EQUIP" /> <!-- Release Agathion's Seal - Uthanka -->
			<skill id="23087" level="1" /> <!-- Uthanka Agathion Cute Trick -->
			<skill id="3267" level="1" type="ON_UNEQUIP" /> <!-- Seal Agathion -->
		</skills>
	</item>
	<item id="20666" name="Valkyrie Hat" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A hat endowed with the Valkyrie's power. <font color=eeaa22>Equipped in the left head accessory slot.</font> -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="isAppearanceable" val="true" />
	</item>
	<item id="20678" name="Gatekeeper Hat" additionalName="Not Available" type="Armor">
		<!-- The item is not available. A hat worn by Gatekeepers. <font color=eeaa22>Equipped in the left head accessory slot.</font> -->
		<set name="icon" val="icon.etc_ertheia2" />
		<set name="default_action" val="EQUIP" />
		<set name="bodypart" val="hairall" />
		<set name="immediate_effect" val="true" />
		<set name="material" val="WOOD" />
		<set name="weight" val="10" />
		<set name="is_sellable" val="false" />
		<set name="is_premium" val="true" />
		<set name="is_oly_restricted" val="true" />
		<set name="isAppearanceable" val="true" />
	</item>
</list>
